#!/usr/bin/env python3
"""Delivery metrics collector (§9 / A.10).

Usage:
  python scripts/delivery_metrics.py --base origin/main
  python scripts/delivery_metrics.py --base origin/main --write

--write вставляет/обновляет блок "## Harness metrics" в
delivery/active/verify-report.md. Exit 0 всегда: это отчёт, не гейт
(гейт на наличие блока — в delivery_check.py на фазе handoff).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACTIVE = ROOT / "delivery" / "active"
STATUS = ACTIVE / "STATUS.md"
VERIFY = ACTIVE / "verify-report.md"

# Правка любого из этих путей = harness усилен (§5.4): новый oracle / hook / eval.
HARDENING_PATHS = (
    "scripts/lint/",
    "delivery/evals/",
    ".pre-commit-config.yaml",
    ".github/workflows/",
    "scripts/delivery_check.py",
    "scripts/okf_sync_gate.py",
)
DOC_PREFIXES = ("delivery/", "knowledge/")


def git(*args: str) -> str:
    try:
        out = subprocess.run(["git", *args], capture_output=True, text=True, check=False)
    except FileNotFoundError:
        return ""
    return out.stdout if out.returncode == 0 else ""


def first_commit(path: str, needle: str | None = None) -> tuple[str, datetime] | None:
    """Первый коммит, добавивший path (или впервые внёсший needle в path).

    needle — РЕГУЛЯРКА (pickaxe-regex), а не литерал: в STATUS.md поля размечены
    markdown-жирным (`**phase:** handoff`), поэтому поиск литерала "phase: handoff"
    не находил ничего и метрики молча выходили пустыми.
    """
    args = ["log", "--reverse", "--format=%H %aI"]
    if needle:
        args += [f"-S{needle}", "--pickaxe-regex"]
    else:
        args.append("--diff-filter=A")
    args += ["--", path]
    for line in git(*args).splitlines():
        sha, _, iso = line.partition(" ")
        if sha and iso:
            try:
                return sha, datetime.fromisoformat(iso.strip())
            except ValueError:
                return None
    return None


def hours_between(a: datetime, b: datetime) -> str:
    delta = (b - a).total_seconds() / 3600
    return f"{delta:.1f}h" if delta < 48 else f"{delta / 24:.1f}d"


def collect(base: str) -> dict[str, str]:
    m: dict[str, str] = {}

    if not git("rev-parse", "--verify", "--quiet", base).strip():
        m["_error"] = f"ref '{base}' unavailable (shallow clone?)"
        return m
    merge_base = git("merge-base", base, "HEAD").strip() or base

    code_files = doc_files = added = deleted = 0
    hardened: list[str] = []
    for line in git("diff", "--numstat", f"{merge_base}..HEAD").splitlines():
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        a, d, path = parts
        if path.startswith(HARDENING_PATHS):
            hardened.append(path)
        if path.startswith(DOC_PREFIXES):
            doc_files += 1
            continue
        code_files += 1
        added += int(a) if a.isdigit() else 0
        deleted += int(d) if d.isdigit() else 0

    m["files_touched / loc_diff"] = (
        f"{code_files} code (+{doc_files} process docs) / +{added}/-{deleted} (net {added - deleted:+d})"
    )
    m["commits"] = git("rev-list", "--count", f"{merge_base}..HEAD").strip() or "0"

    spec_created = first_commit("delivery/active/spec.md")
    spec_ok = first_commit("delivery/active/STATUS.md", r"human_ok_spec:\**[ \t]*yes")
    if spec_created and spec_ok:
        m["time_to_accepted_spec"] = hours_between(spec_created[1], spec_ok[1])
    elif spec_created:
        m["time_to_accepted_spec"] = "spec drafted, not yet accepted"
    else:
        m["time_to_accepted_spec"] = "n/a (no spec.md in history — class S?)"

    handoff = first_commit("delivery/active/STATUS.md", r"phase:\**[ \t]*handoff")
    if handoff:
        after = git("rev-list", "--count", f"{handoff[0]}..HEAD").strip() or "0"
        m["rework_after_done"] = f"{after} commit(s) after first phase: handoff"
    else:
        m["rework_after_done"] = "0 (handoff not declared yet)"

    m["harness_hardened"] = f"yes — {', '.join(sorted(set(hardened))[:4])}" if hardened else "no"
    m["implement_retries"] = "MANUAL — fills from session log"
    m["verify_fails_before_green"] = "MANUAL — count red verify runs (CI run list)"
    m["est_token_or_cost"] = "MANUAL / n/a"
    return m


def render(m: dict[str, str], base: str) -> str:
    if "_error" in m:
        rows = f"| (collection failed) | {m['_error']} |"
    else:
        rows = "\n".join(f"| {k} | {v} |" for k, v in m.items())
    return (
        "## Harness metrics (this shipment)\n\n"
        f"<!-- generated by scripts/delivery_metrics.py --base {base} -->\n\n"
        "| Metric | Value |\n|---|---|\n"
        f"{rows}\n\n"
        "MANUAL-поля заполняет агент/человек на handoff. Если "
        "`verify_fails_before_green >= 2` при `harness_hardened: no` — по §9.2 "
        "добавь oracle/breaker/hook в этой же поставке.\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="origin/main")
    ap.add_argument("--write", action="store_true", help="upsert block into verify-report.md")
    args = ap.parse_args()

    block = render(collect(args.base), args.base)

    if not args.write:
        print(block)
        return 0

    if not ACTIVE.is_dir():
        print("no delivery/active/ — nothing to write", file=sys.stderr)
        return 0
    text = VERIFY.read_text(encoding="utf-8") if VERIFY.is_file() else "# Verify report\n\n"
    # Заменить существующий блок целиком, чтобы не копить дубли на повторных прогонах.
    pattern = re.compile(r"(?ms)^## Harness metrics.*?(?=^## |\Z)")
    text = pattern.sub("", text).rstrip() + "\n\n" + block
    VERIFY.write_text(text, encoding="utf-8")
    print(f"metrics written to {VERIFY.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
